### ISSUE TITLE
Total amount problem

### ISSUE THREAD

**Issue by Chintu12a** [smritifotedar/pizza#1]
Can help me to solve the total amount issue in pizza project. It showing me price of all pizzas not total amount like 300300300 not rs900 like that

**Comment by smritifotedar** [comment]
I got the same error. I will send you next mail in which I'll tell you
what to do.

**Comment by smritifotedar** [comment]
![WhatsApp Image 2020-12-18 at 13 07 20](https://user-images.githubusercontent.com/73025731/102589015-63004900-4134-11eb-8daf-743069c93665.jpeg)

This error is coming because js is reading this element from database as a string.. You just have to convert it back to int
Ek variable mai store the value of price & then change that variable into integer
Open your cartcontroller.js

**Comment by Chintu12a** [comment]
Thank you for your answer.

**Comment by smritifotedar** [comment]
you are welcome

**Comment by Chintu12a** [comment]
can you tell me about my error.

>

**Comment by smritifotedar** [comment]
What do you mean?

**Comment by Chintu12a** [comment]
Error in webpack file.
Can't find module
